params:
  keycdn: https://osuny-1b4da.kxcdn.com
  cookie_banner:
    enable: true
    blank: true
    page: https://gdpr.eu/cookies/
  posts:
    list:
      show_categories: false
      truncate_description: 0 # Set to 0 to disable truncate
  pages:
    list:
      truncate_description: 0 # Set to 0 to disable truncate