name: Test with example

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set new submodule in new branch on Osuny Example
        uses: actions/checkout@v4
        with:
          repository: noesya/osuny-example
          submodules: 'recursive'
          token: ${{ secrets.OSUNY_EXAMPLE_TOKEN }}
      - run: |
          git config user.name osuny-bot
          git config user.email osuny@noesya.coop
          git checkout -b theme--${GITHUB_HEAD_REF}
          cd themes/osuny-hugo-theme-aaa
          git checkout ${GITHUB_HEAD_REF}
          cd ../..
          git add .
          git commit -m "Updated theme to ${GITHUB_HEAD_REF} branch."
          git push