name: Test with example

on:
  push:
    branches:
      - percy-workflow-example
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set new submodule in new branch on Osuny Example
        uses: actions/checkout@v4
        with:
          repository: noesya/osuny-example
          submodules: 'recursive'
          token: ${{ secrets.OSUNY_EXAMPLE_TOKEN }}
      - run: |
          git config user.name osuny-bot
          git config user.email osuny@noesya.coop
          echo "== Creating new branch =="
          git checkout -b theme--${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "== Navigating to theme =="
          cd themes/osuny-hugo-theme-aaa
          echo "== Fetching origin =="
          git fetch origin
          echo "== Checking out to branch ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} =="
          git checkout ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "== Navigating back to root =="
          cd ../..
          echo "== Pushing branch =="
          git add .
          git commit -m "Updated theme to ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} branch."
          git push -f origin theme--${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}